### ISSUE TITLE
Default value for home directory.

### ISSUE THREAD

**Issue by bert-willekens** [DavidGoodwin/pureftp-user-admin#1]
Hi

Thanks for this tool!

I tried to edit the Zend code to prefill the home directory field. Unfortunately I was not successful. I don't know the Zend framework.
I want to limit my users (or at least point them in the right direction) to only share subfolders of a specific path.

Other options can be:
- Configuration of a prefix to the path entered in the form.
- Prefill that can not be deleted in the input field.
- Prefill with the combination of some hard coded path appended with the entered user name.

Which one would be feasible to implement?

Thanks
Bert

**Comment by DavidGoodwin** [comment]
Technically they all could be implemented.

If the username is what is mapping onto the directory path, I think you'd find it easiest to just ignore whatever is in the database cell for the homedir, and instead just change the SQL query that PureFTPd is using - 
e.g

from : 

MYSQLGetDir     SELECT concat(dir, "/./") FROM logins WHERE username="\L"

to 

MYSQLGetDir     SELECT concat('/path/to/somewhere/', "\L") 

Alternatively, yes, the PHP code could be changed so different value(s) are added. The simplest approach might be to just support some optional callable to be called each time a write is made to that field, and you could put whatever custom logic you wanted into it?

e.g.
```PHP
$config['pre_save_user_callable'] = function(array $user) { 
    if($user['username'] == 'fred') { // some token optional check
        if(!preg_match('/^foo/', $user['dir'])) { 
           $user['dir'] = 'foo/something/someting' . $user['dir']; // prefix dir with foo/something..
       }
    }
    return $user;
};
```

**Comment by DavidGoodwin** [comment]
(the 'hook' isn't implemented, but should be fairly simple to add, assuming I understand what you're after)
